config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "home/index"
  root to: "home#index"

  resources :cut_yields, only: [ :index, :new, :create, :destroy ] do
    collection do
      post :calculate
    end
  end

  resources :miter_frames, only: [ :index, :new, :create, :destroy ] do
    collection do
      post :calculate
    end
  end

  resources :projects
  # This is a blank app! Pick your first screen, build out the RCAV, and go from there. E.g.:
  # get("/your_first_screen", { :controller => "pages", :action => "first" })
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @resource = User.new
    @resource_name = :user
    @devise_mapping = Devise.mappings[:user]
  end
end

app/views/home/index.html.erb
<% if policy(:home).show_links? %>
  <div class = "d-flex justify-content-center align-items-center gap-4" >
    <div class="icon-with-text">
      <%= link_to new_cut_yield_path, id: "cut_yields", class: "svg-cut-yields-link", aria: { label: "Create a new cut yield"} do %>

        <%= image_tag 'https://www.svgrepo.com/show/219275/saw.svg', width: 96, alt: "Saw icon for new cut yield" %>
        <div class="new-cut-bubble">
          <span>New Cut Yield</span>
        </div>
      <% end %>
    </div>
    <div class="icon-with-text">
      <%= link_to new_miter_frame_path, id: "miter_frames", class: "svg-miter-link", aria: { label: "Create new miter frame"} do %>

        <%= image_tag 'https://www.svgrepo.com/show/361672/angle.svg', width: 96, alt: "Angle icon for new miter frame" %>
        <div class="new-cut-bubble">
          <span>New Miter Frame</span>
        </div>

      <% end %>
    </div>
  </div>
<% else%>
  <div id="login-container" class= "login-home">
    <h2>Log in</h2>

    <%= form_for(@resource, as: @resource_name, url: session_path(@resource_name)) do |f| %>
      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email", required: true, aria: {required: true} %>
      </div>

      <div class="field">
        <%= f.label :password %><br />
        <%= f.password_field :password, autocomplete: "current-password", required: true, aria: {required: true} %>
      </div>
      <br>
      <% if @devise_mapping.rememberable? %>
        <div class="field">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %>
        </div>
      <% end %>
      <br>
      <%= f.submit "Log in", class: "login-button" %>
    <% end %>
    <br>
    <%= link_to "Sign Up", new_user_registration_path, class: "sign-up-button" %>

  <% end %>