config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "home/index"
  root to: "home#index"

  resources :cut_yields, only: [ :index, :new, :create, :destroy ] do
    collection do
      post :calculate
    end
  end

  resources :miter_frames, only: [ :index, :new, :create, :destroy ] do
    collection do
      post :calculate
    end
  end

  resources :projects
  # This is a blank app! Pick your first screen, build out the RCAV, and go from there. E.g.:
  # get("/your_first_screen", { :controller => "pages", :action => "first" })
end

app/models/cut_yield.rb
# == Schema Information
#
# Table name: cut_yields
#
#  id                :bigint           not null, primary key
#  board_length      :decimal(7, 4)
#  board_length_unit :string
#  name              :string
#  piece_length      :decimal(7, 4)
#  piece_length_unit :string
#  pieces_count      :integer
#  waste_length      :decimal(7, 4)
#  waste_length_unit :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  user_id           :bigint           not null
#
# Indexes
#
#  index_cut_yields_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class CutYield < ApplicationRecord
  belongs_to :user
  before_save :calculate_waste_length_decimal, :calculate_pieces_count

  SAW_THICKNESS = Rational(1, 8)

  attr_accessor :board_length_whole, :board_length_numerator, :board_length_denominator
  attr_accessor :piece_length_whole, :piece_length_numerator, :piece_length_denominator

  before_validation :combine_board_length, :combine_piece_length

  def format_fraction(rational)
    return "" if rational.nil?

    whole = rational.to_i
    remainder = rational - whole

    if remainder.zero?
      whole.to_s
    elsif whole.zero?
      "#{remainder.numerator}/#{remainder.denominator}"
    else
      "#{whole} #{remainder.numerator}/#{remainder.denominator}"
    end
  end

  def board_length_display
    format_fraction(board_length&.to_r)
  end

  def piece_length_display
    format_fraction(piece_length&.to_r)
  end

  def waste_length_display
    format_fraction(calculated_waste_length&.to_r)
  end

  def combine_board_length
    return if board_length_whole.blank? && board_length_numerator.blank? && board_length_denominator.blank?

    whole = board_length_whole.to_i
    numerator = board_length_numerator.to_i
    denominator = board_length_denominator.to_i

    denominator = 1 if denominator.zero?
    self.board_length = Rational(whole) + Rational(numerator, denominator)
  end

  def combine_piece_length
    return if piece_length_whole.blank? && piece_length_numerator.blank? && piece_length_denominator.blank?

    whole = piece_length_whole.to_i
    numerator = piece_length_numerator.to_i
    denominator = piece_length_denominator.to_i

    denominator = 1 if denominator.zero?
    self.piece_length = Rational(whole) + Rational(numerator, denominator)
  end

  def calculated_waste_length
    pieces = calculated_pieces_count
    total_cuts = pieces
    board_length - (pieces * piece_length + total_cuts * SAW_THICKNESS )
  end

  def calculated_pieces_count
    return 0 if piece_length.to_f.zero?
    ((board_length + SAW_THICKNESS) / (piece_length + SAW_THICKNESS)).floor
  end

  def calculate_waste_length_decimal
    self.waste_length = calculated_waste_length.to_f
  end

  def calculate_pieces_count
    self.pieces_count = calculated_pieces_count
  end
end

app/controllers/cut_yields_controller.rb
class CutYieldsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cut_yield, only: [ :destroy ]

  # GET /cut_yields or /cut_yields.json
  def index
    @cut_yields = SearchService.new(current_user, CutYield, params[:query]).call

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /cut_yields/new
  def new
    @cut_yield = CutYield.new
  end

  # POST /cut_yields or /cut_yields.json
  def create
    @cut_yield = current_user.cut_yields.new(cut_yield_params)

    if @cut_yield.save
      flash[:notice] = "Cut yield created successfully!"
      redirect_to cut_yields_path
    else
      flash.now[:alert] = "There was a problem creating a cut yield."
      render :index
    end
  end

  # DELETE /cut_yields/1 or /cut_yields/1.json
  def destroy
    @cut_yield.destroy
    redirect_to cut_yields_path, notice: "Cut yield was successfully destroyed."
  end

  private

  def set_cut_yield
    @cut_yield = current_user.cut_yields.find(params[:id])
  end

  def cut_yield_params
    params.require(:cut_yield).permit(
      :name,
      :board_length_whole,
      :board_length_numerator,
      :board_length_denominator,
      :piece_length_whole,
      :piece_length_numerator,
      :piece_length_denominator,
    )
  end
end

app/views/cut_yields/_cut_yield.html.erb
<div class="yield-bubble">

  <div class="cut-name">
    <strong><%= cut_yield.name&.capitalize %></strong>
  </div>
  <br>
  <div class="cut-specs-text">
    <p>Board Length: <%= cut_yield.board_length_display %></p>
    <p>Piece Length: <%= cut_yield.piece_length_display %></p>
    <p>Pieces Count: <%= cut_yield.pieces_count%></p>
    <p>Waste Length: <%= cut_yield.waste_length_display %></p>
  </div>
  <br>
  <div class="bubble-actions">
    <%= link_to "Delete", cut_yield_path(cut_yield), method: :delete, data: { confirm: "Are you sure?" }, class: "delete-text" %>
  </div>
</div>

app/views/cut_yields/_form.html.erb
<%= form_with(model: cut_yield) do |form| %>
  <% if cut_yield.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cut_yield.errors.count, "error") %> prohibited this cut_yield from being saved:</h2>

      <ul>
        <% cut_yield.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label : , style: "display: block" %>
    <%= form.text_field :  %>
  </div>

  <div>
    <%= form.label :board_length, style: "display: block" %>
    <%= form.text_field :board_length %>
  </div>

  <div>
    <%= form.label :board_length_unit, style: "display: block" %>
    <%= form.text_field :board_length_unit %>
  </div>

  <div>
    <%= form.label : , style: "display: block" %>
    <%= form.text_field :  %>
  </div>

  <div>
    <%= form.label :piece_length, style: "display: block" %>
    <%= form.text_field :piece_length %>
  </div>

  <div>
    <%= form.label :piece_length_unit, style: "display: block" %>
    <%= form.text_field :piece_length_unit %>
  </div>

  <div>
    <%= form.label : , style: "display: block" %>
    <%= form.text_field :  %>
  </div>

  <div>
    <%= form.label :pieces_count, style: "display: block" %>
    <%= form.number_field :pieces_count %>
  </div>

  <div>
    <%= form.label : , style: "display: block" %>
    <%= form.text_field :  %>
  </div>

  <div>
    <%= form.label :waste_length, style: "display: block" %>
    <%= form.text_field :waste_length %>
  </div>

  <div>
    <%= form.label :waste_length_unit, style: "display: block" %>
    <%= form.text_field :waste_length_unit %>
  </div>

  <div>
    <%= form.label : , style: "display: block" %>
    <%= form.text_field :  %>
  </div>

  <div>
    <%= form.label :project_id, style: "display: block" %>
    <%= form.text_field :project_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cut_yields/edit.html.erb
<% content_for :title, "Editing cut yield" %>

<h1>Editing cut yield</h1>

<%= render "form", cut_yield: @cut_yield %>

<br>

<div>
  <%= link_to "Show this cut yield", @cut_yield %> |
  <%= link_to "Back to cut yields", cut_yields_path %>
</div>

app/views/cut_yields/index.html.erb
<h1>Cut Yields</h1>

<%= form_with url: cut_yields_path, method: :get, local: false, html: {id: "search-form"} do |f| %>
  <%= f.text_field :query, id: "search-cut-yield", placeholder: "Search by name...", class: "search-box" %>
<% end %>

<!-- <% link_to "New Cut Yield", new_cut_yield_path, class: "btn" %> -->
<div class="cut-yields-container">
  <%= render partial: "cut_yield", collection: @cut_yields %>
</div>

app/views/cut_yields/index.js.erb
document.querySelector(".cut-yields-container").innerHTML = `
<%= j(render partial: "cut_yield", collection: @cut_yields) %>
`;

app/views/cut_yields/new.html.erb
<h1>Cut Yields</h1>

<%= form_with(model: @cut_yield, local: true, id: "cut-yield-form") do |f| %>

  <div>
    <h3>Project Name</h3>
    <%= f.label :name, "Cut Yield Name" %>
    <%= f.text_field :name%>
  </div>

  <div>
    <h3> Board Length </h3>
    <%= f.label :board_length_whole, "Whole" %>
    <%= f.number_field :board_length_whole, id: "board_length_whole"%>

    <div class="tooltip-wrapper">
      <%= f.label :board_length_numerator, "Numerator" %>
      <%= f.select :board_length_numerator, options_for_select((0..31).to_a), {}, {id: "board_length_numerator", aria: { describedby: "board-numerator-tooltip"}} %>
      <span id="board-numerator-tooltip" class="tooltip-text">Select numerator of board length in inches</span>
    </div>

    <div class="tooltip-wrapper">
      <%= f.label :board_length_denominator, "Denominator" %>
      <%= f.select :board_length_denominator, options_for_select([1,2,4,8,16,32]), {}, {id: "board_length_denominator", aria: { describedby: "board-denominator-tooltip" }} %>
      <span id="board-denominator-tooltip" class="tooltip-text">Select denominator of board length in inches</span>
    </div>
  </div>

  <div>
    <h3> Piece Length </h3>
    <%= f.label :piece_length_whole, "Whole" %>
    <%= f.number_field :piece_length_whole, id: "piece_length_whole" %>

    <div class="tooltip-wrapper">
      <%= f.label :piece_length_numerator, "Numerator" %>
      <%= f.select :piece_length_numerator, options_for_select((0..31).to_a), {},  {id: "piece_length_numerator", aria: { describedby: "piece-numerator-tooltip"}} %>
      <span id="piece-numerator-tooltip" class="tooltip-text">Select numerator of piece length in inches</span>
    </div>

    <div class="tooltip-wrapper">
      <%= f.label :piece_length_denominator, "Denominator" %>
      <%= f.select :piece_length_denominator, options_for_select([1,2,4,8,16,32]), {}, {id: "piece_length_denominator", aria: { describedby: "piece-denominator-tooltip" }} %>
      <span id="piece-denominator-tooltip" class="tooltip-text">Select denominator of piece length in inches</span>
    </div>
  </div>

  <div>
    <h3>Results</h3>
    <p>Pieces Count: <span id="pieces-count-preview">0</span></p>
    <p>Waste Length: <span id="waste-length-preview">0</span> in</p>
  </div>

  <%= f.submit "Save Cut Yield" %>

<% end %>

app/views/cut_yields/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cut_yield %>

<div>
  <%= link_to "Edit this cut yield", edit_cut_yield_path(@cut_yield) %> |
  <%= link_to "Back to cut yields", cut_yields_path %>

  <%= button_to "Destroy this cut yield", @cut_yield, method: :delete %>
</div>