config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "home/index"
  root to: "home#index"

  resources :cut_yields, only: [ :index, :new, :create, :destroy ] do
    collection do
      post :calculate
    end
  end

  resources :miter_frames, only: [ :index, :new, :create, :destroy ] do
    collection do
      post :calculate
    end
  end

  resources :projects
  # This is a blank app! Pick your first screen, build out the RCAV, and go from there. E.g.:
  # get("/your_first_screen", { :controller => "pages", :action => "first" })
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "PlankPro" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <header>
      <nav class="header-nav">
        <div class="logo">
          <h2>PlankPro</h2>
        </div>

        <% if user_signed_in? %>
          Logged in as <%= current_user.email %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          <%= link_to "Home", home_index_path, class: "nav-link" %>
          <%= link_to "Cut Yields", cut_yields_path, class: "nav-link" %>
          <%= link_to "Miter Frames", miter_frames_path, class: "nav-link" %>
        <% end %>
      </nav>

    </header>
    <%= render "shared/flash" %>
    <%= yield %>

  </body>
</html>